description: "A little learning library in Lua."
title: "LULL"
logo: "img/banner.png"

# CRITICAL: Replace 'your-repository-name' with your actual repo name
baseurl: "/lull"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

search_enabled: true

footer_content: "© 2026 Tim Menzies. MIT license."
gh_edit_link: true
gh_edit_link_text: "edit this page"
gh_edit_repository: "https://github.com/timm/lull"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"  # opens in github UI


enable_copy_code_button: true
